### ISSUE TITLE
Windows port

### ISSUE THREAD

**Issue by robotsinthesun** [robotsinthesun/monkeyprint#23]
The GUI needs to be translated from GTK to Qt to allow users to run Monkeyprint on Windows.

**Comment by thevisad** [comment]
I actually run this under Windows 10 currently with the Ubuntu add on from anniversary edition and XMing. I also ran it under Windows 7 prior to this with little effort using an alternative method of supporting bash.

https://puu.sh/t9fWy/93f0e28d0c.PNG

**Comment by robotsinthesun** [comment]
Monkeyprint now runs on Windows as of version 0.14.0 :)
