### ISSUE TITLE
Tilt Servo

### ISSUE THREAD

**Issue by pc6b** [robotsinthesun/monkeyprint#5]
Hi Paul,

As discussed recently I suppose to change the stepper motor to a RC servo in the tilt mechanism. Steppers are loosing steps and after a few hundred revolvings in large projects the end position drifts away. RC servos doesn't have this problems if they stall lightly against a spring coil on to the end position of the vat. They are also much cheaper.

Kind regards

Bruno

**Comment by robotsinthesun** [comment]
Works now with G-Code support.
